spring.application.name=bff-agendador

usuario.url=http://localhost:8080
tarefas.url=http://localhost:8081
server.port=8083
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
